---
version: "3.8"

services:
  web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/mcmanager
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/server-instances:/home/app/data/instances
      - ./data/server-packs:/home/app/data/packs
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
